export const ErrorCodes = {
  // Validation Errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_FIELD: "MISSING_FIELD",
  INVALID_FORMAT: "INVALID_FORMAT",

  // Resource Errors
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  CONFLICT: "CONFLICT",

  // Authentication Errors
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",

  // AI Errors
  AI_SERVICE_ERROR: "AI_SERVICE_ERROR",
  AI_TIMEOUT: "AI_TIMEOUT",
  AI_RATE_LIMIT: "AI_RATE_LIMIT",
  INVALID_AI_RESPONSE: "INVALID_AI_RESPONSE",

  // File Errors
  FILE_ERROR: "FILE_ERROR",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  FILE_UPLOAD_ERROR: "FILE_UPLOAD_ERROR",

  // Parse Errors
  PARSE_ERROR: "PARSE_ERROR",
  PDF_PARSE_ERROR: "PDF_PARSE_ERROR",
  DOCX_PARSE_ERROR: "DOCX_PARSE_ERROR",

  // Rate Limit
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // Export Errors
  EXPORT_ERROR: "EXPORT_ERROR",
  PDF_GENERATION_ERROR: "PDF_GENERATION_ERROR",
  DOCX_GENERATION_ERROR: "DOCX_GENERATION_ERROR",

  // System Errors
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  DATABASE_ERROR: "DATABASE_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
